"""not unique image

Revision ID: 1c9b40aa9869
Revises: 6499574b0ca4
Create Date: 2023-08-13 17:21:57.775584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9b40aa9869'
down_revision = '6499574b0ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
