"""Delete functionality

Revision ID: 949b1c453e05
Revises: 001d9724aa98
Create Date: 2023-08-10 15:38:55.503429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949b1c453e05'
down_revision = '001d9724aa98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
